version: "3"
services:
  csrfdb:
    image: mysql:8.0.29
    container_name: csrf-mysql-server-8029
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: oVkOdTfOhxdD3KQzXtIye0dBkvwM4Xi7YVdEd5jC
      MYSQL_DATABASE: csrf
      MYSQL_USER: csrfuser
      MYSQL_PASSWORD: rDbA0qwtjey9TJ6Z7pEFtN5pEAc1ebqvvlwWkEnY
    volumes:
      - ./db/mysql.sql:/docker-entrypoint-initdb.d/init.sql
  csrfweb:
    depends_on:
      - csrfdb
    container_name: csrf-php-web
    build: ./web/
    environment:
      DB_HOST: csrfdb
      DB_USER: csrfuser
      DB_PASSWORD: rDbA0qwtjey9TJ6Z7pEFtN5pEAc1ebqvvlwWkEnY
      DB_DATABASE: csrf
    ports:
      - "8002:80"
    volumes:
      - ./web/src:/var/www/html
