version: "3"
services:
  xssdb:
    image: mysql:8.0.29
    container_name: xss-mysql-server-8029
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: iXBiTfjDYawSiO1RqLofJV5TVhbxItZA7V9iFtrw
      MYSQL_DATABASE: xss
      MYSQL_USER: xssuser
      MYSQL_PASSWORD: yQLOfQ1YeNaJxNYkiLdBzfsW2Z7gmfYVGtN9QgHH
    volumes:
      - ./db/mysql.sql:/docker-entrypoint-initdb.d/init.sql
  xssweb:
    depends_on:
      - xssdb
    container_name: xss-php-web
    build: ./web/
    environment:
      DB_HOST: xssdb
      DB_USER: xssuser
      DB_PASSWORD: yQLOfQ1YeNaJxNYkiLdBzfsW2Z7gmfYVGtN9QgHH
      DB_DATABASE: xss
    ports:
      - "8001:80"
    volumes:
      - ./web/src:/var/www/html
